Web/registrasi/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'), 
	url(r'^update/(?P<update_id>[0-9]+)$', views.update, name='update'),
	url(r'^create/$', views.create, name='create'),
	url(r'^$', views.list, name='list'),
]

Web/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^admin/', admin.site.urls),
	url(r'^registrasi/', include('registrasi.urls', namespace="registrasi")),
] 

Web/registrasi/models.py
from django.db import models

# Create your models here.

class Registrasi(models.Model):
	nama_lengkap	= models.CharField(max_length=100)
	email			= models.CharField(max_length=100)
	jenis_kelamin	= models.CharField(max_length=20)
	alamat			= models.CharField(max_length=100)

	def __str__(self):
		return "{}.{}". format(self.id,self.nama_lengkap)

Web/registrasi/forms.py
from django import forms
from . models import Registrasi

class RegisForm(forms.ModelForm):
	class Meta:
		model = Registrasi
		fields =[
			'nama_lengkap',
			'email',
			'jenis_kelamin',
			'alamat',
		]

		

		widgets = {
		'nama_lengkap': forms.TextInput(
				attrs ={
					'class':'form-control',
					'placeholder':'Masukan Nama Lengkap Anda',
					}
					),

			  'email': forms.TextInput(
				attrs ={
					'class':'form-control',
					'placeholder':'Isi Dengan Alamat Email Anda',
					}
					),

	  'jenis_kelamin': forms.Select(
				attrs ={
					'class':'form-control',
					},
				choices =[
					('Laki-laki','Laki-laki'),
					('Perempuan','Perempuan'),
					]
				),
	  'alamat'		 : forms.Textarea(
	  		attrs ={
	  			'class':'form-control',
	  		}	)
}

Web/registrasi/views.py
from django.shortcuts import render, redirect

from . models import Registrasi
from . forms import RegisForm

def delete(request, delete_id):
	Registrasi.objects.filter(id=delete_id).delete()
	return redirect('registrasi:list')

def update(request, update_id):
	akun_update = Registrasi.objects.get(id=update_id)

	data ={
		'nama_lengkap' 		: akun_update.nama_lengkap,
		'email' 			: akun_update.email,
		'jenis_kelamin'		: akun_update.jenis_kelamin,
		'alamat'			: akun_update.alamat,
	}
	akun_form = RegisForm(request.POST or None, initial=data, instance=akun_update)

	if request.method == 'POST':
		if akun_form.is_valid():
			akun_form.save()

		return redirect('registrasi:list')

	context = {
		'page_title':'Update Data',
		'akun_form':akun_form,
	}
	return render(request,'registrasi/create.html', context)

def create(request):
	akun_form = RegisForm(request.POST or None)

	if request.method == 'POST':
		if akun_form.is_valid():
			akun_form.save()

		return redirect('registrasi:list')

	context = {
		'page_title':'Tambah Orang :',
		'akun_form':akun_form,
	}
	return render(request,'registrasi/create.html', context)

def list(request):
	semua_akun = Registrasi.objects.all()
	context = {
		'judul':'Data Pengguna',
		'heading':'Selamat Datang ',
		'subheading':'Di Halamat Registrasi',
		'semua_akun':semua_akun,
	}

	return render(request, 'registrasi/list.html',context)

Web/views.py
from django.shortcuts import render

def index(request):
	context = {
		'judul':'JURNAL PRAKERIN | WEB REGISTRATIONS',
		'heading':'Welcome To My Website',
		'subheading':'Selamat Datang di halaman website saya yang berisi tentang berbagai macam informasi',
	}
	return render(request,'index.html', context)

Web/registrasi/templates/registrasi/create.html
{% extends "base.html" %}
{% load static %}

{% block app_css %}
	<link rel="stylesheet" type="text/css" href="{% static "registrasi/css/style.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "registrasi/css/font.css" %}">
	{% endblock app_css %}

{% block section-contact %}
<section class="contact" id="contact">
		<div class="container" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
			<div class="row">
				<div class="col-sm-12">
					<div class="headerText text-center">
						<h2>{{page_title}}</h2>
					</div>
				</div>
			</div>
			<div class="row clearfix">
				<div class="offset-sm-2 col-sm-8">
						<form method="POST">
							{% csrf_token %}
							<table>
								{{akun_form.as_table}}
							</table>
						<button type="submit" class="btn btn-info">Kirim</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock section-contact %}

Web/registrasi/templates/registrasi/list.html
{% extends "base.html" %}
{% load static %}

{% block app_css %}
	<link rel="stylesheet" type="text/css" href="{% static "registrasi/css/style.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "registrasi/css/font.css" %}">
	{% endblock app_css %}

{% block section-2 %}
		<section class="sec2" id="adventure">
		<div class="container h100">
			<div class="contentBox h100">
				<div data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
					<h1>{{heading}}</h1>
					<p>{{subheading}}</p>
					<a href="{% url 'registrasi:create' %}" class="btn btnD1">Segera Registrasi!</a>
				</div>
			</div>
		</div>
	</section>
{% endblock section-2 %}

{% block section-blog %}
	<section class="blog" id="blog">
		<div class="container" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
			<div class="row">
				<div class="offset-sm-2 col-sm-8">
					<div class="headerText text-center">
						<h2>-Data Pengunjung-</h2>
					</div>
				</div>
			</div><br>
			<table class="table table-bordered" style="color: #fff">
			  <thead class="text-center bg-light text-dark">
			    <tr>
			      <th scope="col">No</th>
			      <th scope="col">Nama Lengkap</th>
			      <th scope="col">Email</th>
			      <th scope="col">Jenis Kelamin</th>
			      <th scope="col">Alamat</th>
			      <th scope="col">Action</th>
			    </tr>
			  </thead>
			  <tbody>
			  {% for akun in semua_akun %}
				    <tr>
				      <th scope="row">{{forloop.counter}}</th>
				      <td>{{akun.nama_lengkap}}</td>
				      <td>{{akun.email}}</td>
				      <td>{{akun.jenis_kelamin}}</td>
				      <td>{{akun.alamat}}</td>
				      <td><a class="btn btn-danger" href="{% url 'registrasi:delete' akun.id %}">Delete</a> &nbsp;&nbsp;&nbsp;&nbsp; <a class="btn btn-warning" href="{% url 'registrasi:update' akun.id %}">Update</a></td>
				    </tr>
			{% endfor %}
			</tbody>
			</table>
		</div>
	</section>
{% endblock section-blog %}

Web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="widht=device-widht,initial-scale=1.0">
	<meta charset="utf-8">
	<title>{{judul}}</title>

	{% block app_css %}
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/font.css" %}">
	{% endblock app_css %}	

	{% include "snippets/style.html" %}

	<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
	

</head>
<body>
	<header>
		{% include "snippets/navbar.html" %}
	</header>

	{% block content-1 %}
	
	{% endblock content-1 %}

	{% block section-1 %}
	
	{% endblock section-1 %}

	{% block section-2 %}
	
	{% endblock section-2 %}

	{% block section-blog %}

	{% endblock section-blog %}

	{% block section-contact %}

	{% endblock section-contact %}
	
	{% include "snippets/scripts.html" %}

	 <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  	 <script>
     	AOS.init();
  	 </script>
	<script type="text/javascript">
		$(document).scroll(function() {
			$('.navbar').toggleClass('scrolled', $(this).scrollTop() > $('.navbar').height());
		});
	</script>
</body>
</html>

Web/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content-1 %}
	<div class="jumbotron jumbotron-fluid height100p banner" id="home">
 		 <div class="container h100">
    		<div class="contentBox h100">
    			<div data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
    				<h1>{{heading}}</h1>
    				<p>{{subheading}}</p>
    			</div>
    		</div>
  		</div>
	</div>
{% endblock content-1 %}

{% block section-1 %}
	<section class="sec1" id="explore">
		<div class="container">
			<div class="row">
				<div class="offset-sm-2 col-sm-8">
					<div class="headerText text-center">
						<h2 data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">Explore The World</h2>
						<p data-aos="fade-up" data-aos-duration="1000" data-aos-delay="400">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat.</p>
					</div>
				</div>		
			</div>
			<div class="row">
				<div class="col-sm-4">
					<div class="placeBox" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
						<div class="imgBx">
							<img src="{% static "img/img1.jpg" %}" class="img-fluid">
						</div>
						<div class="content">
							<h3>Place Name<br><span>Country Name</span></h3>
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="placeBox" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="500">
						<div class="imgBx">
							<img src="{% static "img/img2.jpg" %}" class="img-fluid">
						</div>
						<div class="content">
							<h3>Place Name<br><span>Country Name</span></h3>
						</div>
					</div>
				</div>
				<div class="col-sm-4">
					<div class="placeBox" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="1000">
						<div class="imgBx">
							<img src="{% static "img/img3.jpg" %}" class="img-fluid">
						</div>
						<div class="content">
							<h3>Place Name<br><span>Country Name</span></h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock section-1 %}


{% block section-2 %}
	<section class="sec2" id="adventure">
		<div class="container h100">
			<div class="contentBox h100">
				<div data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
					<h1>Adventure Is Everywhere</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
					quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
					consequat.</p>
					<a href="#" class="btn btnD1">Read More</a>
				</div>
			</div>
		</div>
	</section>
{% endblock section-2 %}

{% block section-blog %}
	<section class="blog" id="blog">
		<div class="container" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
			<div class="row">
				<div class="offset-sm-2 col-sm-8">
					<div class="headerText text-center">
						<h2>Our Lates Post</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
						cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
						proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="blogpost" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
						<div class="imgBx">
							<img src="{% static "img/img1.jpg" %}" class="img-fluid">
						</div>
						<div class="content">
							<h1>Pesona Indonesia</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
							<a href="#" class="btn btnD2">Read More</a>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="blogpost" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="500">
						<div class="imgBx">
							<img src="{% static "img/img2.jpg" %}" class="img-fluid">
						</div>
						<div class="content">
							<h1>Pesona Indonesia</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
							<a href="#" class="btn btnD2">Read More</a>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="blogpost" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
						<div class="imgBx">
							<img src="{% static "img/img3.jpg" %}" class="img-fluid">
						</div>
						<div class="content">
							<h1>Pesona Indonesia</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
							<a href="#" class="btn btnD2">Read More</a>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="blogpost" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="500">
						<div class="imgBx">
							<img src="{% static "img/img1.jpg" %}" class="img-fluid">
						</div>
						<div class="content">
							<h1>Pesona Indonesia</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
							proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
							<a href="#" class="btn btnD2">Read More</a>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock section-blog %}


{% block section-contact %}
<section class="contact" id="contact">
		<div class="container" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="0">
			<div class="row">
				<div class="col-sm-12">
					<div class="headerText text-center">
						<h2>Contact Us</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
					</div>
				</div>
			</div>
			<div class="row clearfix">
				<div class="offset-sm-2 col-sm-8">
						<form>
							<div class="form-group">
								<label>Name</label>
								<input type="text" name="" class="form-control">
							</div>
							<div class="form-group">
								<label>Email</label>
								<input type="text" name="" class="form-control">
							</div>
							<div class="form-group">
								<label>Phone</label>
								<input type="text" name="" class="form-control">
							</div>
							<div class="form-group">
								<label>Massage</label>
								<textarea class="form-control textarea" name=""></textarea>
							</div>
							<div class="form-group">
								<button class="btn btnD1">Send</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock section-contact %}

Web/templates/snippets/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark  fixed-top" id="myNav">
			<div class="container">
  			<a class="navbar-brand" href="#"><img src="{% static "img/g3.png" %}" style="height: 40px"></a>
  				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  				</button>

  				<div class="collapse navbar-collapse" id="navbarSupportedContent">
   					 <ul class="navbar-nav ml-lg-auto">
      						<li class="nav-item active">
        						<a class="nav-link" href="{% url "index" %}">Home <span class="sr-only">(current)</span></a>
      						</li>
      						<li class="nav-item">
        						<a class="nav-link" href="{% url "registrasi:list" %}">Registrasi</a>
     						 </li>
     						 <li class="nav-item">
        						<a class="nav-link" href="#">Blog</a>
     						 </li>
     						 <li class="nav-item">
        						<a class="nav-link" href="/admin/">Admin</a>
     						 </li>
    				</ul>
   			</div>
 		 </div>
	</nav>

Web/templates/snippets/scripts.html
{% load static %}
	<script src="{% static "vendor/popper/popper.js" %}" type="text/javascript"></script>
	<script src="{% static "vendor/jquery/jquery.js" %}" type="text/javascript"></script>
	<script src="{% static "vendor/bootstrap/bootstrap.js" %}" type="text/javascript"></script>
	<script src="{% static "js/scrooling.js" %}" type="text/javascript"></script>

Web/templates/snippets/style.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/bootstrap.css" %}">